import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import {
  ProgressStats,
  ProgressStatsDocument,
  PeriodStats,
} from './progress-stats.schema';
import { UpdateProgressStatsDto } from '../interfaces/progress-stats.interfaces';

@Injectable()
export class ProgressStatsService {
  constructor(
    @InjectModel('ProgressStats')
    private progressStatsModel: Model<ProgressStatsDocument>,
  ) {}

  async getProgressStatsByUserId(userId: string): Promise<ProgressStats> {
    const stats = await this.progressStatsModel
      .findOne({ userId })
      .populate('userId')
      .exec();

    if (!stats) {
      // Create default stats if not exists
      return this.createDefaultStats(userId);
    }

    return stats;
  }

  async updateProgressStats(
    userId: string,
    updateData: UpdateProgressStatsDto,
  ): Promise<ProgressStats> {
    const updatedStats = await this.progressStatsModel
      .findOneAndUpdate(
        { userId },
        {
          ...updateData,
          autoGeneratedAt: new Date(),
        },
        {
          new: true,
          upsert: true,
        },
      )
      .populate('userId')
      .exec();

    if (!updatedStats) {
      throw new NotFoundException(
        `Progress stats for user ${userId} not found`,
      );
    }

    return updatedStats;
  }

  async regenerateProgressStats(userId: string): Promise<ProgressStats> {
    // This method would typically fetch raw data from PhysicalData and TrainingPlan collections
    // and calculate the statistics. For now, we'll simulate the calculation.

    const last7DaysStats = this.calculateLast7DaysStats(userId);
    const last30DaysStats = this.calculateLast30DaysStats(userId);

    return this.updateProgressStats(userId, {
      last7Days: last7DaysStats,
      last30Days: last30DaysStats,
      autoGeneratedAt: new Date(),
    });
  }

  async getAllProgressStats(): Promise<ProgressStats[]> {
    return this.progressStatsModel.find().populate('userId').exec();
  }

  async deleteProgressStats(userId: string): Promise<void> {
    const result = await this.progressStatsModel.deleteOne({ userId }).exec();
    if (result.deletedCount === 0) {
      throw new NotFoundException(
        `Progress stats for user ${userId} not found`,
      );
    }
  }

  async bulkRegenerateStats(userIds?: string[]): Promise<ProgressStats[]> {
    const filter = userIds ? { userId: { $in: userIds } } : {};
    const users = await this.progressStatsModel.find(filter).exec();

    const regeneratedStats: ProgressStats[] = [];

    for (const user of users) {
      try {
        const stats = await this.regenerateProgressStats(
          user.userId.toString(),
        );
        regeneratedStats.push(stats);
      } catch (error) {
        console.error(
          `Failed to regenerate stats for user ${user.userId}:`,
          error,
        );
      }
    }

    return regeneratedStats;
  }

  async getStatsLastUpdatedBefore(date: Date): Promise<ProgressStats[]> {
    return this.progressStatsModel
      .find({ autoGeneratedAt: { $lt: date } })
      .populate('userId')
      .exec();
  }

  private async createDefaultStats(userId: string): Promise<ProgressStats> {
    const defaultStats = new this.progressStatsModel({
      userId,
      last7Days: {
        weightDiff: 0,
        fatDiff: 0,
        workoutsCompleted: 0,
      },
      last30Days: {
        weightDiff: 0,
        fatDiff: 0,
        workoutsCompleted: 0,
      },
      autoGeneratedAt: new Date(),
    });

    return defaultStats.save();
  }

  private calculateLast7DaysStats(_userId: string): PeriodStats {
    // TODO: Implement actual calculation from PhysicalData and TrainingPlan collections
    // This would involve:
    // 1. Get physical data from last 7 days and 7 days before that
    // 2. Calculate weight and fat differences
    // 3. Count completed workouts in last 7 days

    const sevenDaysAgo = new Date();
    sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

    // Placeholder implementation - replace with actual calculations
    return {
      weightDiff: 0, // Calculate from PhysicalData collection
      fatDiff: 0, // Calculate from PhysicalData collection
      workoutsCompleted: 0, // Calculate from TrainingPlan or workout completion logs
    };
  }

  private calculateLast30DaysStats(_userId: string): PeriodStats {
    // TODO: Implement actual calculation from PhysicalData and TrainingPlan collections
    // Similar to calculateLast7DaysStats but for 30 days period

    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

    // Placeholder implementation - replace with actual calculations
    return {
      weightDiff: 0, // Calculate from PhysicalData collection
      fatDiff: 0, // Calculate from PhysicalData collection
      workoutsCompleted: 0, // Calculate from TrainingPlan or workout completion logs
    };
  }

  async updateWorkoutCount(
    userId: string,
    increment: number = 1,
  ): Promise<ProgressStats> {
    const stats = await this.getProgressStatsByUserId(userId);

    return this.updateProgressStats(userId, {
      last7Days: {
        ...stats.last7Days,
        workoutsCompleted: stats.last7Days.workoutsCompleted + increment,
      },
      last30Days: {
        ...stats.last30Days,
        workoutsCompleted: stats.last30Days.workoutsCompleted + increment,
      },
    });
  }
}
