import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import {
  ProgressStats,
  ProgressStatsDocument,
  PeriodStats,
} from './progress-stats.schema';
import { getIdString } from '../../utils/helpers';

/**
 * What may be written to a stats document.
 *
 * Wider than `UpdateProgressStatsDto` on purpose: the DTO is the shape a
 * *client* may send and excludes the derived `workoutsCompleted`, while
 * `regenerateProgressStats` writes it. Narrowing happens at the controller
 * boundary, where it belongs.
 */
interface ProgressStatsPatch {
  last7Days?: Partial<PeriodStats>;
  last30Days?: Partial<PeriodStats>;
}

/** Shape returned by the physical-data projection used for diffing */
interface MeasurementPoint {
  weightKg: number;
  bodyFatPercent?: number;
  dateRecorded: Date;
}

@Injectable()
export class ProgressStatsService {
  private readonly logger = new Logger(ProgressStatsService.name);

  constructor(
    @InjectModel('ProgressStats')
    private progressStatsModel: Model<ProgressStatsDocument>,
    @InjectModel('PhysicalData')
    private physicalDataModel: Model<MeasurementPoint>,
    @InjectModel('TrainingPlan')
    private trainingPlanModel: Model<unknown>,
    @InjectModel('WorkoutSession')
    private workoutSessionModel: Model<unknown>,
  ) {}

  async getProgressStatsByUserId(userId: string): Promise<ProgressStats> {
    const stats = await this.progressStatsModel
      .findOne({ userId })
      .populate('userId')
      .exec();

    if (!stats) {
      // Create default stats if not exists
      return this.createDefaultStats(userId);
    }

    return stats;
  }

  /**
   * `UpdateProgressStatsDto` is the shape a *client* may send, and it excludes
   * the derived workout count. `regenerateProgressStats` writes that count, so
   * the internal signature is wider than the DTO on purpose — the narrowing
   * happens at the controller boundary, where it belongs.
   */
  async updateProgressStats(
    userId: string,
    updateData: ProgressStatsPatch,
  ): Promise<ProgressStats> {
    const updatedStats = await this.progressStatsModel
      .findOneAndUpdate(
        { userId },
        {
          ...updateData,
          autoGeneratedAt: new Date(),
        },
        {
          new: true,
          upsert: true,
        },
      )
      .populate('userId')
      .exec();

    if (!updatedStats) {
      throw new NotFoundException(
        `Progress stats for user ${userId} not found`,
      );
    }

    return updatedStats;
  }

  async regenerateProgressStats(userId: string): Promise<ProgressStats> {
    const [last7DaysStats, last30DaysStats] = await Promise.all([
      this.calculatePeriodStats(userId, 7),
      this.calculatePeriodStats(userId, 30),
    ]);

    // autoGeneratedAt is stamped by updateProgressStats itself; passing it here
    // was redundant, and it is no longer part of the DTO so clients cannot
    // backdate their own stats.
    return this.updateProgressStats(userId, {
      last7Days: last7DaysStats,
      last30Days: last30DaysStats,
    });
  }

  async getAllProgressStats(): Promise<ProgressStats[]> {
    return this.progressStatsModel.find().populate('userId').exec();
  }

  async deleteProgressStats(userId: string): Promise<void> {
    const result = await this.progressStatsModel.deleteOne({ userId }).exec();
    if (result.deletedCount === 0) {
      throw new NotFoundException(
        `Progress stats for user ${userId} not found`,
      );
    }
  }

  async bulkRegenerateStats(userIds?: string[]): Promise<ProgressStats[]> {
    const filter = userIds ? { userId: { $in: userIds } } : {};
    const users = await this.progressStatsModel.find(filter).exec();

    const regeneratedStats: ProgressStats[] = [];

    for (const user of users) {
      // `userId` is an ObjectId here (or a populated user on other reads), so
      // it goes through getIdString rather than being stringified directly —
      // the plain form yields "[object Object]" for the populated case.
      const id = getIdString(user.userId);
      try {
        regeneratedStats.push(await this.regenerateProgressStats(id));
      } catch (error) {
        this.logger.error(
          `Failed to regenerate stats for user ${id}`,
          error instanceof Error ? error.stack : String(error),
        );
      }
    }

    return regeneratedStats;
  }

  async getStatsLastUpdatedBefore(date: Date): Promise<ProgressStats[]> {
    return this.progressStatsModel
      .find({ autoGeneratedAt: { $lt: date } })
      .populate('userId')
      .exec();
  }

  private async createDefaultStats(userId: string): Promise<ProgressStats> {
    const defaultStats = new this.progressStatsModel({
      userId,
      last7Days: {
        weightDiff: 0,
        fatDiff: 0,
        workoutsCompleted: 0,
      },
      last30Days: {
        weightDiff: 0,
        fatDiff: 0,
        workoutsCompleted: 0,
      },
      autoGeneratedAt: new Date(),
    });

    return defaultStats.save();
  }

  /**
   * Build the real stats for a rolling window ending now.
   *
   * weightDiff/fatDiff are (latest reading in window − baseline), where the
   * baseline is the most recent reading at or before the window start. Using
   * the last reading *before* the window rather than the first one inside it
   * means a single measurement taken today still yields a meaningful delta.
   * When there is no baseline we fall back to the earliest in-window reading;
   * with fewer than two points there is no movement to report, so 0.
   *
   * A positive diff means "went up" — the frontend decides whether that is
   * good, since it depends on the user's target (bulk vs cut).
   */
  private async calculatePeriodStats(
    userId: string,
    days: number,
  ): Promise<PeriodStats> {
    const since = new Date();
    since.setDate(since.getDate() - days);

    const [measurements, workoutsCompleted] = await Promise.all([
      this.getMeasurementsForWindow(userId, since),
      this.countWorkoutDays(userId, since),
    ]);

    const { baseline, latest } = measurements;

    // Body fat is optional per reading, so it gets its own pair of points
    return {
      weightDiff: this.round1(this.diff(baseline?.weightKg, latest?.weightKg)),
      fatDiff: this.round1(
        this.diff(baseline?.bodyFatPercent, latest?.bodyFatPercent),
      ),
      workoutsCompleted,
    };
  }

  /**
   * Resolve the baseline and latest measurement for a window. Body-fat points
   * are resolved separately because a reading may omit `bodyFatPercent`.
   */
  private async getMeasurementsForWindow(
    userId: string,
    since: Date,
  ): Promise<{
    baseline?: Partial<MeasurementPoint>;
    latest?: Partial<MeasurementPoint>;
  }> {
    const userObjectId = new Types.ObjectId(userId);

    const [inWindow, priorWeight, priorFat] = await Promise.all([
      this.physicalDataModel
        .find({ userId: userObjectId, dateRecorded: { $gte: since } })
        .sort({ dateRecorded: 1 })
        .select('weightKg bodyFatPercent dateRecorded')
        .lean()
        .exec(),
      this.physicalDataModel
        .findOne({ userId: userObjectId, dateRecorded: { $lt: since } })
        .sort({ dateRecorded: -1 })
        .select('weightKg dateRecorded')
        .lean()
        .exec(),
      this.physicalDataModel
        .findOne({
          userId: userObjectId,
          dateRecorded: { $lt: since },
          bodyFatPercent: { $ne: null },
        })
        .sort({ dateRecorded: -1 })
        .select('bodyFatPercent dateRecorded')
        .lean()
        .exec(),
    ]);

    const withFat = inWindow.filter((m) => m.bodyFatPercent != null);

    // Fall back to the earliest in-window reading when nothing precedes it
    const weightBaseline = priorWeight ?? inWindow[0];
    const fatBaseline = priorFat ?? withFat[0];

    return {
      baseline: {
        weightKg: weightBaseline?.weightKg,
        bodyFatPercent: fatBaseline?.bodyFatPercent,
      },
      latest: {
        weightKg: inWindow[inWindow.length - 1]?.weightKg,
        bodyFatPercent: withFat[withFat.length - 1]?.bodyFatPercent,
      },
    };
  }

  /**
   * A completed workout is a distinct calendar day on which the user logged at
   * least one set, so several exercises logged the same day count once.
   *
   * Two sources, unioned by day:
   *   - `WorkoutSession`, the collection sessions are written to now;
   *   - the legacy `days[].exercises[].sets[].history[]` still embedded in
   *     training plans.
   *
   * Keeping both means the number does not drop for anyone whose history has
   * not been backfilled yet, and does not double-count once it has — a day
   * present in both sources is still one day. Once the backfill has run
   * everywhere and new writes only go to sessions, the legacy branch can go.
   */
  private async countWorkoutDays(userId: string, since: Date): Promise<number> {
    const [sessionDays, legacyDays] = await Promise.all([
      this.sessionWorkoutDays(userId, since),
      this.legacyWorkoutDays(userId, since),
    ]);

    return new Set([...sessionDays, ...legacyDays]).size;
  }

  /** Distinct YYYY-MM-DD strings from the WorkoutSession collection. */
  private async sessionWorkoutDays(
    userId: string,
    since: Date,
  ): Promise<string[]> {
    const result = await this.workoutSessionModel
      .aggregate<{ _id: string }>([
        {
          $match: {
            userId: new Types.ObjectId(userId),
            performedAt: { $gte: since },
          },
        },
        {
          $group: {
            _id: {
              $dateToString: { format: '%Y-%m-%d', date: '$performedAt' },
            },
          },
        },
      ])
      .exec();

    return result.map((r) => r._id);
  }

  /** Distinct YYYY-MM-DD strings still embedded in training plan documents. */
  private async legacyWorkoutDays(
    userId: string,
    since: Date,
  ): Promise<string[]> {
    const result = await this.trainingPlanModel
      .aggregate<{ _id: string }>([
        { $match: { userId: new Types.ObjectId(userId) } },
        { $unwind: '$days' },
        { $unwind: '$days.exercises' },
        { $unwind: '$days.exercises.sets' },
        { $unwind: '$days.exercises.sets.history' },
        {
          $match: {
            'days.exercises.sets.history.date': { $gte: since },
          },
        },
        {
          $group: {
            _id: {
              $dateToString: {
                format: '%Y-%m-%d',
                date: '$days.exercises.sets.history.date',
              },
            },
          },
        },
      ])
      .exec();

    return result.map((r) => r._id);
  }

  private diff(from?: number | null, to?: number | null): number {
    if (from == null || to == null) return 0;
    return to - from;
  }

  /** Stats are display values; keep them to one decimal place. */
  private round1(value: number): number {
    return Math.round(value * 10) / 10;
  }
}
