import { z } from 'zod';
import { Schema, HydratedDocument, Model } from 'mongoose';

// Define period stats schema
export const periodStatsSchema = z.object({
  weightDiff: z
    .number({
      invalid_type_error: 'Weight difference must be a number',
    })
    .default(0),
  fatDiff: z
    .number({
      invalid_type_error: 'Fat difference must be a number',
    })
    .default(0),
  workoutsCompleted: z
    .number({
      invalid_type_error: 'Workouts completed must be a number',
    })
    .int()
    .nonnegative()
    .default(0),
});

// Define the Zod schema for validation
export const progressStatsSchema = z.object({
  userId: z.string({
    required_error: 'User ID is required',
    invalid_type_error: 'User ID must be a string',
  }),
  last7Days: periodStatsSchema.default({
    weightDiff: 0,
    fatDiff: 0,
    workoutsCompleted: 0,
  }),
  last30Days: periodStatsSchema.default({
    weightDiff: 0,
    fatDiff: 0,
    workoutsCompleted: 0,
  }),
  autoGeneratedAt: z.date().default(() => new Date()),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});

// Create types from Zod schema
export type ProgressStats = z.infer<typeof progressStatsSchema>;
export type PeriodStats = z.infer<typeof periodStatsSchema>;

// Define Mongoose PeriodStats schema
const PeriodStatsMongooseSchema = {
  weightDiff: { type: Number, default: 0 },
  fatDiff: { type: Number, default: 0 },
  workoutsCompleted: { type: Number, default: 0, min: 0 },
};

// Define Mongoose schema
export const ProgressStatsSchema = new Schema(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      unique: true,
    },
    last7Days: {
      type: PeriodStatsMongooseSchema,
      default: {
        weightDiff: 0,
        fatDiff: 0,
        workoutsCompleted: 0,
      },
    },
    last30Days: {
      type: PeriodStatsMongooseSchema,
      default: {
        weightDiff: 0,
        fatDiff: 0,
        workoutsCompleted: 0,
      },
    },
    autoGeneratedAt: { type: Date, required: true, default: Date.now },
  },
  {
    timestamps: true,
    validateBeforeSave: true,
  },
);

// Add indexes
ProgressStatsSchema.index({ userId: 1 });
ProgressStatsSchema.index({ autoGeneratedAt: -1 });
ProgressStatsSchema.index({ 'last7Days.workoutsCompleted': -1 });
ProgressStatsSchema.index({ 'last30Days.workoutsCompleted': -1 });

// Add validation middleware
ProgressStatsSchema.pre('save', function (next) {
  const result = progressStatsSchema.safeParse(this.toObject());
  if (!result.success) {
    next(new Error(result.error.message));
  }
  next();
});

// Type for a hydrated document
export type ProgressStatsDocument = HydratedDocument<ProgressStats>;

// Type for the model
export type ProgressStatsModel = Model<ProgressStatsDocument>;