import { Type } from 'class-transformer';
import {
  IsInt,
  IsNumber,
  IsOptional,
  Min,
  ValidateNested,
} from 'class-validator';

// These were plain `interface`s. class-validator cannot attach metadata to an
// interface, so at runtime the parameter type erased to `Object`, the
// ValidationPipe skipped it entirely, and any shape at all reached Mongo.
// Classes with decorators are what make the pipe actually run.

export class PeriodStatsDto {
  @IsOptional()
  @IsNumber()
  weightDiff?: number;

  @IsOptional()
  @IsNumber()
  fatDiff?: number;

  @IsOptional()
  @IsInt()
  @Min(0)
  workoutsCompleted?: number;
}

export class UpdateProgressStatsDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => PeriodStatsDto)
  last7Days?: PeriodStatsDto;

  @IsOptional()
  @ValidateNested()
  @Type(() => PeriodStatsDto)
  last30Days?: PeriodStatsDto;

  // `autoGeneratedAt` is deliberately absent: the service stamps it itself, so
  // accepting it from the client would only let someone backdate their stats.
}

export class IncrementWorkoutCountDto {
  @IsOptional()
  @IsInt()
  @Min(1)
  increment?: number;
}
