import { Type } from 'class-transformer';
import { IsNumber, IsOptional, ValidateNested } from 'class-validator';

// These were plain `interface`s. class-validator cannot attach metadata to an
// interface, so at runtime the parameter type erased to `Object`, the
// ValidationPipe skipped it entirely, and any shape at all reached Mongo.
// Classes with decorators are what make the pipe actually run.

export class PeriodStatsDto {
  @IsOptional()
  @IsNumber()
  weightDiff?: number;

  @IsOptional()
  @IsNumber()
  fatDiff?: number;

  // `workoutsCompleted` is deliberately absent, like `autoGeneratedAt` below.
  // It is derived from logged sessions by `calculatePeriodStats`; there was
  // also a `POST /:userId/workout-completed` that let a client raise the
  // stored counter by any number it liked, so the same figure had two sources
  // that were guaranteed to disagree. Only the derived one survives, and the
  // whitelist pipe now strips this field if a client sends it.
}

export class UpdateProgressStatsDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => PeriodStatsDto)
  last7Days?: PeriodStatsDto;

  @IsOptional()
  @ValidateNested()
  @Type(() => PeriodStatsDto)
  last30Days?: PeriodStatsDto;

  // `autoGeneratedAt` is deliberately absent: the service stamps it itself, so
  // accepting it from the client would only let someone backdate their stats.
}
