import { PeriodStats } from '../objects/progress-stats/progress-stats.schema';

export interface UpdateProgressStatsDto {
  last7Days?: PeriodStats;
  last30Days?: PeriodStats;
  autoGeneratedAt?: Date;
}
